// Дасгалын төвийн каталог — worksheets.html ба plan.html хуваалцана
window.WS_LIST=[
  ['6-р анги',[
    ['arav-toymloh-6.html','Аравтын бутархайг тоймлох (аравт·зуут·мянгат)'],
    ['arav6-nemeh.html','Аравтын бутархай нэмэх (гурван гишүүнт · хүнд)'],
    ['arav6-hasah.html','Аравтын бутархай хасах (дараалсан · хүнд)'],
    ['arav6-urjih.html','Аравтын бутархай үржих (2 орон × аравт/бүхэл)'],
    ['arav6-huvaah.html','Аравтын бутархай хуваах (аравт хуваагчаар)'],
    ['arav6-ilerhiilel.html','Аравтын бутархай илэрхийлэл (хаалт·олон үйлдэл)'],
    ['arav6-holimog.html','Аравт ба энгийн бутархай холимог (хүнд)'],
    ['numshul-nemeh-hasah-12.html','Тоон шулуун дээрх нэмэх/хасах'],
    ['negativ-too-100.html','Сөрөг тоо нэмэх/хасах (100)'],
    ['temdegt-nemeh-hasah-60.html','Бүхэл тоо нэмэх/хасах (бүх хэлбэр)'],
    ['temdegt-urjhuv-20.html','Эерэг сөрөг үржих/хуваах'],
    ['temdegt-ilerhiilel-20.html','Эерэг сөрөг илэрхийлэл'],
    ['anhny-too-100.html','Анхны тоонууд (1–100)'],
    ['anhny-zadlal-16.html','Анхны үржигдэхүүнд задлах'],
    ['hieh-hbeh-16.html','ХИЕХ ба ХБЕХ (баганан)'],
    ['izil-huvaari-16.html','Ижил хуваарьтай болгох'],
    ['huvari-arav-protsent-16.html','Бутархай·аравт·хувь шилжүүлэх'],
    ['butarhai-uildluud-10.html','Энгийн бутархайн үйлдлүүд (+ − × ÷)'],
    ['butarhai-huvaah-16.html','Бутархай хуваах — эргүүлж үржүүлэх'],
    ['algebr-gishuun-negtgeh-16.html','Ижил гишүүд нэгтгэх'],
    ['algebr-haalt-zadlah-16.html','Хаалт задлах (нэг хаалт)'],
    ['algebr-hyalbarchlah-14.html','Алгебр илэрхийлэл хялбарчлах (хаалт задлах)'],
    ['butarhai-hura-18.html','Бутархай хураах (засагдах)'],
    ['butarhai-holimog-16.html','Холимог ↔ энгийн бус бутархай'],
    ['butarhai-ekvivalent-24.html','Эквивалент бутархай (дутуу тоо)'],
    ['butarhai-jish-6.html','Бутархай жиших (хөндлөн·энгийн бус·холимог)'],
    ['tegshitgel-6.html','Тэгшитгэл (сөрөгтэй хоёр алхам)'],
    ['hamar-ongo.html','Хамар өнцөг 1'],
    ['hamar-ongo-2.html','Хамар өнцөг 2 (илэрхийлэлтэй)'],
    ['bosoo-ongo.html','Босоо өнцөг 1'],
    ['bosoo-ongo-2.html','Босоо өнцөг 2 (илэрхийлэлтэй)'],
    ['gurvaljin-ongo.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 1'],
    ['gurvaljin-ongo-2.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['olon-ongogt-ongo.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 1 (4·5·6)'],
    ['olon-ongogt-ongo-2.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
  ]],
  ['7-р анги',[
    ['toony-modul-1-7.html','Тооны модул-1'],
    ['toony-modul-2-7.html','Тооны модул-2'],
    ['toony-modul-3-7.html','Тооны модул-3'],
    ['buhel-nemeh-hasah-1-7.html','Бүхэл тоон нэмэх, хасах-1'],
    ['buhel-nemeh-hasah-2-7.html','Бүхэл тоон нэмэх, хасах-2'],
    ['buhel-nemeh-hasah-3-7.html','Бүхэл тоон нэмэх, хасах-3'],
    ['buhel-urjih-huvaah-1-7.html','Бүхэл тоон үржүүлэх, хуваах-1'],
    ['buhel-urjih-huvaah-2-7.html','Бүхэл тоон үржүүлэх, хуваах-2'],
    ['buhel-urjih-huvaah-3-7.html','Бүхэл тоон үржүүлэх, хуваах-3'],
    ['kub-zereg-1-7.html','Куб зэрэг ба куб язгуур-1'],
    ['kub-zereg-2-7.html','Куб зэрэг ба куб язгуур-2'],
    ['kub-zereg-3-7.html','Куб зэрэг ба куб язгуур-3'],
    ['anhny-too-zadlah-7.html','Анхны тоон үржигдэхүүнд задлах-1'],
    ['anhny-too-zadlah-2-7.html','Анхны тоон үржигдэхүүнд задлах-2'],
    ['hieh-hbeh-1-7.html','ХИЕХ ба ХБЕХ-1'],
    ['hieh-hbeh-2-7.html','ХИЕХ ба ХБЕХ-2'],
    ['hieh-hbeh-3-7.html','ХИЕХ ба ХБЕХ-3'],
    ['arawtiin-zereg-uildel-7.html','10-ын зэрэг-1'],
    ['aravtiin-zereg-bichleg-7.html','10-ын зэрэг-2'],
    ['arawtaar-urjih-huvaah-7.html','10-ын зэрэг-3'],
    ['arawtiin-butarhai-jishih-7.html','Аравтын бутархайг жиших-1'],
    ['arawtiin-butarhai-eremblel-7.html','Аравтын бутархайг жиших-2'],
    ['toog-toimloh-7.html','Тоог тоймлох-1'],
    ['toimlol-tootsoolol-7.html','Тоог тоймлох-2'],
    ['toimloh-urvuu-bodlogo-7.html','Тоог тоймлох-3'],
    ['holimog-uildel-butarhai-7.html','Хялбар аргаар тооцоолох-1'],
    ['tohiromjtoi-daraalal-7.html','Хялбар аргаар тооцоолох-2'],
    ['engiin-butarhai-huraah-jishih-7.html','Энгийн бутархайг хураах-1'],
    ['butarhai-huvirgalt-jishilt-7.html','Энгийн бутархайг хураах-2'],
    ['engiin-butarhai-nemeh-hasah-7.html','Бутархайн нэмэх, хасах-1'],
    ['holimog-too-nemeh-hasah-7.html','Бутархайн нэмэх, хасах-2'],
    ['butarhai-nemeh-bodlogo-7.html','Бутархайн нэмэх, хасах-3'],
    ['engiin-butarhai-urjih-huvaah-7.html','Бутархайн үржүүлэх, хуваах-1'],
    ['holimog-too-urjih-huvaah-7.html','Бутархайн үржүүлэх, хуваах-2'],
    ['butarhai-olon-alham-7.html','Бутархайн үржүүлэх, хуваах-3'],
    ['butarhai-protsent-1-7.html','Бутархай ба процент-1'],
    ['butarhai-protsent-2-7.html','Бутархай ба процент-2'],
    ['butarhai-protsent-huesnegt-7.html','Бутархай ба процент-3'],
    ['hodolgoon-ajil-bodlogo-7.html','Хөдөлгөөний бодлого-1'],
    ['dundaj-hurd-bodlogo-7.html','Хөдөлгөөний бодлого-2'],
    ['ajil-hesgiin-bodlogo-7.html','Ажлын бодлого-1'],
    ['protsentiin-bodlogo-7.html','Процентын бодлого-1'],
    ['hemjeenii-protsent-oloh-7.html','Процентын бодлого-2'],
    ['protsent-ugen-bodlogo-7.html','Процентын бодлого-3'],
    ['osolt-buuraltiin-protsent-7.html','Өсөлт, бууралтын процент-1'],
    ['hyamdral-osoltiin-bodlogo-7.html','Өсөлт, бууралтын процент-2'],
    ['haritsaa-hylbar-7.html','Харьцааг хялбарчлах-1'],
    ['haritsaa-negj-7.html','Харьцааг хялбарчлах-2'],
    ['haritsaa-butarhai-7.html','Харьцааг хялбарчлах-3'],
    ['proports-1-7.html','Пропорц-1'],
    ['proports-undsen-chanar-7.html','Пропорц-2'],
    ['proports-bodlogo-7.html','Пропорц-3'],
    ['proports-2-7.html','Харьцаа ба процент-1'],
    ['haritsaa-protsent-7.html','Харьцаа ба процент-2'],
    ['haritsaagaar-huvaah-7.html','Харьцаагаар хуваах-1'],
    ['haritsaagaar-huvaah-2-7.html','Харьцаагаар хуваах-2'],
    ['niilber-yalgavar-haritsaa-7.html','Харьцаагаар хуваах-3'],
    ['haritsaa-hemjee-7.html','Харьцаагаар хуваах-4'],
    ['shuud-proports-1-7.html','Шууд пропорционал хамаарал-1'],
    ['shuud-proports-2-7.html','Шууд пропорционал хамаарал-2'],
    ['shuud-proports-3-7.html','Шууд пропорционал хамаарал-3'],
    ['esreg-uzegdel-1-7.html','Эсрэг үзэгдэл ба магадлал-1'],
    ['esreg-uzegdel-2-7.html','Эсрэг үзэгдэл ба магадлал-2'],
    ['esreg-uzegdel-3-7.html','Эсрэг үзэгдэл ба магадлал-3'],
    ['esreg-uzegdel-4-7.html','Эсрэг үзэгдэл ба магадлал-4'],
    ['hoyor-shoo-1-7.html','Хоёр шоо орхих туршилт-1'],
    ['hoyor-shoo-2-7.html','Хоёр шоо орхих туршилт-2'],
    ['hoyor-shoo-3-7.html','Хоёр шоо орхих туршилт-3'],
    ['zoos-negdsen-turshilt-7.html','Зоос ба нэгдсэн туршилт'],
    ['shudarga-toglom-7.html','Нэгдсэн туршилт ба шударга тоглоом'],
    ['sanamsargui-too-1-7.html','Санамсаргүй тоо сонгох магадлал-1'],
    ['sanamsargui-too-2-7.html','Санамсаргүй тоо сонгох магадлал-2'],
    ['sanamsargui-too-3-7.html','Санамсаргүй тоо сонгох магадлал-3'],
    ['sanamsargui-songolt-7.html','Санамсаргүй сонголтын магадлал'],
    ['tosootoi-gishuud-7.html','Төсөөтэй гишүүд эмхэтгэх'],
    ['haalt-zadlah-7.html','Хаалт задлах'],
    ['ilerhiilel-utga-7.html','Хялбарчилж утга олох'],
    ['ilerhiilel-aldaa-7.html','Хялбарчлалын алдаа олох'],
    ['zergiin-chanar-7.html','Зэргийн чанарууд-1'],
    ['zereg-chanar-2-7.html','Зэргийн чанарууд-2'],
    ['neg-gishuunt-1-7.html','Нэг гишүүнт-1'],
    ['neg-gishuunt-2-7.html','Нэг гишүүнт-2'],
    ['talbai-perimetr-7.html','Талбай, периметр, эзлэхүүн'],
    ['gishuunchlen-urjuuleh-7.html','Гишүүнчлэн үржүүлэх'],
    ['eronhii-urjigdehuun-7.html','Ерөнхий үржигдэхүүн гаргах'],
    ['shugaman-tegshitgel-1-7.html','Шугаман тэгшитгэл-1'],
    ['shugaman-tegshitgel-2-7.html','Шугаман тэгшитгэл-2'],
    ['tegshitgel-butarhai-7.html','Бутархайтай тэгшитгэл'],
    ['tegshitgel-bodlogo-7.html','Тэгшитгэл зохиох-1'],
    ['tegshitgel-bodlogo-2-7.html','Тэгшитгэл зохиох-2'],
    ['tegshitgel-bodlogo-3-7.html','Тэгшитгэл зохиох-3'],
    ['toon-daraalal-1-7.html','Тоон дараалал-1'],
    ['toon-daraalal-2-7.html','Тоон дараалал-2'],
    ['eronhii-gishuun-7.html','Ерөнхий гишүүн'],
    ['daraallyn-zui-togtol-7.html','Зүй тогтол ба ерөнхий гишүүн'],
    ['dursiin-daraalal-7.html','Дүрсийн дараалал'],
    ['arifmetik-progress-7.html','Арифметик прогресс-1'],
    ['arifmetik-progress-2-7.html','Арифметик прогресс-2'],
    ['arifmetik-huesnegt-7.html','Арифметик прогрессын хүснэгт'],
    ['arifmetik-bodlogo-1-7.html','Арифметик прогрессын бодлого-1'],
    ['arifmetik-bodlogo-2-7.html','Арифметик прогрессын бодлого-2'],
    ['shugaman-funkts-7.html','Шугаман функц'],
    ['shuluuny-tegshitgel-7.html','Шулууны тэгшитгэл'],
    ['shugaman-funkts-2-7.html','Шугаман функцийн хэрэглээ'],
    ['funkts-huesnegt-7.html','Функцийн утгын хүснэгт'],
    ['funkts-graphik-7.html','Функцийн хүснэгт ба график'],
    ['shuud-proportsional-7.html','Шууд пропорционал хамаарал'],
    ['shuud-proportsional-2-7.html','Шууд пропорционалын бодлого'],
    ['daraalal-zui-togtol-12.html','Дарааллын зүй тогтлыг олох'],
    ['arifmetik-progress-12.html','Арифметик прогресс — n дүгээр гишүүн'],
    ['algebr-gishuun-negtgeh-16.html','Ижил гишүүд нэгтгэх'],
    ['algebr-haalt-zadlah-16.html','Хаалт задлах (нэг хаалт)'],
    ['algebr-hyalbarchlah-14.html','Алгебр илэрхийлэл хялбарчлах (хаалт задлах)'],
    ['aravt-zereg-16.html','10-ын бүхэл илтгэгчтэй зэрэг'],
    ['kvadrat-zereg-20.html','Квадрат зэрэг'],
    ['zereg-chanar-30.html','Зэргийн чанарууд (30)'],
    ['ratsional-nemeh-hasah-20.html','Рационал нэмэх/хасах'],
    ['ratsional-urjih-huvaah-20.html','Рационал үржих/хуваах'],
    ['ratsional-toon-ilerhiilel-16.html','Рационал тоон илэрхийлэл'],
    ['neg-olon-gishuunt-20.html','Нэг × олон гишүүнт'],
    ['olon-olon-gishuunt-16.html','Олон × олон гишүүнт'],
    ['olon-gishuunt-emhetgel-20.html','Олон гишүүнт хялбаржуулах'],
    ['standart-emhetgel-16.html','Стандарт хэлбэрт эмхэтгэх'],
    ['niitleg-uurjigdehuun-20.html','Ерөнхий үржигдэхүүн хаалтнаас'],
    ['niitleg-monom-16.html','Ерөнхий үржигдэхүүн (нэг гишүүнт x,y)'],
    ['gishuunchlen-urjih-16.html','Гишүүнчлэн үржүүлж хялбарчлах'],
    ['shugaman-tegshitgel-16.html','Шугаман тэгшитгэл'],
    ['hamar-ongo.html','Хамар өнцөг 1'],
    ['hamar-ongo-2.html','Хамар өнцөг 2 (илэрхийлэлтэй)'],
    ['bosoo-ongo.html','Босоо өнцөг 1'],
    ['bosoo-ongo-2.html','Босоо өнцөг 2 (илэрхийлэлтэй)'],
    ['gurvaljin-ongo.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 1'],
    ['gurvaljin-ongo-2.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['olon-ongogt-ongo.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 1 (4·5·6)'],
    ['olon-ongogt-ongo-2.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['solbison-ongo.html','Солбисон өнцөг (зэрэгцээ шулуун ба огтлогч)'],
    ['gadaad-ongo.html','Гурвалжны гадаад өнцөг'],
  ]],
  ['8-р анги',[
    ['rats-too-1-8.html','Рационал тоо-1'],
    ['rats-too-2-8.html','Рационал тоо-2'],
    ['rats-too-3-8.html','Рационал тоо-3'],
    ['rats-too-4-8.html','Рационал тоо-4'],
    ['rats-too-5-8.html','Рационал тоо-5'],
    ['toimloh-1-8.html','Тоог тоймлох-1'],
    ['toimloh-2-8.html','Тоог тоймлох-2'],
    ['toimloh-3-8.html','Тоог тоймлох-3'],
    ['toimloh-4-8.html','Тоог тоймлох-4'],
    ['toimloh-5-8.html','Тоог тоймлох-5'],
    ['rats-uildel-1-8.html','Рационал тооны үйлдэл-1'],
    ['rats-uildel-2-8.html','Рационал тооны үйлдэл-2'],
    ['rats-uildel-3-8.html','Рационал тооны үйлдэл-3'],
    ['rats-uildel-4-8.html','Рационал тооны үйлдэл-4'],
    ['rats-holimog-1-8.html','Рационал тооны холимог үйлдэл-1'],
    ['rats-holimog-2-8.html','Рационал тооны холимог үйлдэл-2'],
    ['rats-holimog-3-8.html','Рационал тооны холимог үйлдэл-3'],
    ['natural-zereg-1-8.html','Натурал илтгэгчтэй зэрэг-1'],
    ['natural-zereg-2-8.html','Натурал илтгэгчтэй зэрэг-2'],
    ['natural-zereg-3-8.html','Натурал илтгэгчтэй зэрэг-3'],
    ['natural-zereg-4-8.html','Натурал илтгэгчтэй зэрэг-4'],
    ['natural-zereg-5-8.html','Натурал илтгэгчтэй зэрэг-5'],
    ['zeregt-devsh-8.html','Зэрэгт дэвшүүлэх-1'],
    ['zeregt-devsh-2-8.html','Зэрэгт дэвшүүлэх-2'],
    ['yazguur-gargah-8.html','Язгуур гаргах-1'],
    ['yazguur-gargah-2-8.html','Язгуур гаргах-2'],
    ['arav-zereg-1-8.html','10-ын бүхэл илтгэгчтэй зэрэг-1'],
    ['arav-zereg-2-8.html','10-ын бүхэл илтгэгчтэй зэрэг-2'],
    ['standart-helber-8.html','Стандарт хэлбэр-1'],
    ['standart-helber-2-8.html','Стандарт хэлбэр-2'],
    ['protsent-1-8.html','Процент-1'],
    ['protsent-2-8.html','Процент-2'],
    ['protsent-3-8.html','Процент-3'],
    ['protsent-4-8.html','Процент-4'],
    ['protsent-5-8.html','Процент-5'],
    ['protsent-6-8.html','Процент-6'],
    ['protsent-7-8.html','Процент-7'],
    ['protsent-8-8.html','Процент-8'],
    ['masshtab-1-8.html','Масштаб-1'],
    ['masshtab-2-8.html','Масштаб-2'],
    ['masshtab-3-8.html','Масштаб-3'],
    ['haritsaa-1-8.html','Харьцаа-1'],
    ['haritsaa-2-8.html','Харьцаа-2'],
    ['urvuu-1-8.html','Урвуу пропорц-1'],
    ['urvuu-2-8.html','Урвуу пропорц-2'],
    ['urvuu-3-8.html','Урвуу пропорц-3'],
    ['urvuu-4-8.html','Урвуу пропорц-4'],
    ['urvuu-5-8.html','Урвуу пропорц-5'],
    ['olonlog-1-8.html','Олонлог ба үйлдэл-1'],
    ['olonlog-2-8.html','Олонлог ба үйлдэл-2'],
    ['venn-diagram-8.html','Эйлер-Веннийн диаграм-1'],
    ['olonlog-chadal-8.html','Олонлогийн чадал-1'],
    ['olonlog-holimog-1-8.html','Олонлог холимог-1'],
    ['olonlog-holimog-2-8.html','Олонлог холимог-2'],
    ['uzegdel-8.html','Нийцтэй ба нийцгүй үзэгдэл-1'],
    ['egel-uzegdel-8.html','Эгэл үзэгдэл-1'],
    ['uzegdel-niitstei-8.html','Нийцтэй ба нийцгүй үзэгдэл-2'],
    ['uzegdel-holimog-8.html','Үзэгдэл холимог-1'],
    ['magadlal-1-8.html','Үзэгдлийн магадлал-1'],
    ['magadlal-2-8.html','Үзэгдлийн магадлал-2'],
    ['magadlal-3-8.html','Үзэгдлийн магадлал-3'],
    ['magadlal-huvaari-8.html','Магадлалын хуваарь-1'],
    ['niitsgui-negdel-8.html','Нийцгүй үзэгдлийн нэгдэл-1'],
    ['magadlal-holimog-8.html','Магадлал холимог-1'],
    ['mono-1-8.html','Нэг гишүүнт-1'],
    ['mono-2-8.html','Нэг гишүүнт-2'],
    ['mono-3-8.html','Олон гишүүнт-1'],
    ['mono-4-8.html','Олон гишүүнт-2'],
    ['mono-5-8.html','Олон гишүүнт-3'],
    ['mono-6-8.html','Олон гишүүнт-4'],
    ['kvadr-tomyo-1-8.html','Товчилсон үржих-1'],
    ['kvadr-tomyo-2-8.html','Товчилсон үржих-2'],
    ['kvadr-tomyo-3-8.html','Товчилсон үржих-3'],
    ['zadlal-1-8.html','Задлал-1'],
    ['zadlal-2-8.html','Задлал-2'],
    ['zadlal-3-8.html','Задлал-3'],
    ['zadlal-4-8.html','Задлал-4'],
    ['alg-butarhai-8.html','Алгебрын бутархай-1'],
    ['alg-butarhai-2-8.html','Алгебрын бутархай-2'],
    ['alg-butarhai-3-8.html','Алгебрын бутархай-3'],
    ['rats-teng-1-8.html','Рационал тэгшитгэл-1'],
    ['rats-teng-2-8.html','Рационал тэгшитгэл-2'],
    ['rats-teng-3-8.html','Рационал тэгшитгэл-3'],
    ['shts-shugaman-1-8.html','Шугаман систем-1'],
    ['shts-shugaman-2-8.html','Шугаман систем-2'],
    ['shts-shugaman-3-8.html','Шугаман систем-3'],
    ['tents-bish-1-8.html','Тэнцэтгэл биш-1'],
    ['tents-bish-2-8.html','Тэнцэтгэл биш-2'],
    ['tents-bish-3-8.html','Тэнцэтгэл биш-3'],
    ['tents-bish-4-8.html','Тэнцэтгэл биш-4'],
    ['tents-bish-5-8.html','Тэнцэтгэл биш-5'],
    ['daraalal-8.html','Дараалал-1'],
    ['daraalal-2-8.html','Дараалал-2'],
    ['daraalal-3-8.html','Дараалал-3'],
    ['arifm-progress-1-8.html','Арифметик прогресс-1'],
    ['arifm-progress-2-8.html','Арифметик прогресс-2'],
    ['arifm-progress-3-8.html','Арифметик прогресс-3'],
    ['arifm-progress-4-8.html','Арифметик прогресс-4'],
    ['shugaman-funkts-1-8.html','Шугаман функц-1'],
    ['shugaman-funkts-2-8.html','Шугаман функц-2'],
    ['shugaman-funkts-3-8.html','Шугаман функц-3'],
    ['shugaman-funkts-4-8.html','Шугаман функц-4'],
    ['nalalt-shts-8.html','Шулууны налалт-1'],
    ['nalalt-2-8.html','Шулууны налалт-2'],
    ['shts-grafik-8.html','ШТС-ийн график-1'],
    ['shts-grafik-2-8.html','ШТС-ийн график-2'],
    ['urvuu-grafik-8.html','Урвуу пропорционал хамаарал-1'],
    ['urvuu-grafik-2-8.html','Урвуу пропорционал хамаарал-2'],
    ['urvuu-grafik-3-8.html','Урвуу пропорционал хамаарал-3'],
    ['parabol-1-8.html','Парабол-1'],
    ['parabol-2-8.html','Парабол-2'],
    ['parabol-3-8.html','Парабол-3'],
    ['olon-ongogt-1-8.html','Олон өнцөгт-1'],
    ['olon-ongogt-2-8.html','Олон өнцөгт-2'],
    ['olon-diagonal-8.html','Олон өнцөгт-3'],
    ['olon-algebr-8.html','Олон өнцөгт-4'],
    ['paralel-ongog-8.html','Параллель шулуун-1'],
    ['gurvaljin-shugam-8.html','Гурвалжны шугамууд-1'],
    ['medion-hundiin-8.html','Гурвалжны шугамууд-2'],
    ['bissektris-tuv-8.html','Гурвалжны шугамууд-3'],
    ['pifagor-1-8.html','Пифагорын теорем-1'],
    ['pifagor-2-8.html','Пифагорын теорем-2'],
    ['pifagor-durs-8.html','Пифагорын теорем-3'],
    ['pifagor-trapets-8.html','Пифагорын теорем-4'],
    ['pifagor-algebr-8.html','Пифагорын теорем-5'],
    ['pifagor-olon-alham-8.html','Пифагорын теорем-6'],
    ['pifagor-gurval-8.html','Пифагорын теорем-7'],
    ['toirog-ongog-1-8.html','Тойрог ба өнцөг-1'],
    ['toirog-ongog-2-8.html','Тойрог ба өнцөг-2'],
    ['toirog-num-8.html','Тойрог ба өнцөг-3'],
    ['toirog-dorvon-8.html','Тойрог ба өнцөг-4'],
    ['tosootoi-1-8.html','Төсөөтэй дүрсүүд-1'],
    ['tosootoi-2-8.html','Төсөөтэй дүрсүүд-2'],
    ['tosootoi-hemjee-8.html','Төсөөтэй дүрсүүд-3'],
    ['zereg-uildel-12.html','Зэрэгтэй илэрхийлэл — үйлдэл гүйцэтгэх'],
    ['zereg-chanar-hard-10.html','Зэргийн чанар — хүндэрсэн (тооцоол)'],
    ['yazguur-hyalbarchlah-20.html','Язгуур хялбарчлах (үржигдэхүүн гаргах)'],
    ['rats-zereg-yazguur-ilerhiilel-16.html','Зэрэг ба язгууртай илэрхийлэл (хосолсон)'],
    ['rats-zeregt-18.html','Рационал тоог зэрэгт дэвшүүлэх'],
    ['rats-yazguur-gargah-18.html','Рационал тооноос язгуур гаргах'],
    ['kvadrat-yazguur-20.html','Квадрат язгуур'],
    ['kvadrat-yazguur-buhel-20.html','Квадрат язгуур (бүхэл хариутай)'],
    ['kub-zereg-yazguur-16.html','Куб зэрэг ба куб язгуур'],
    ['ratsional-yazguur-20.html','Рационал тооны язгуур'],
    ['rats-zereg-yazguur-16.html','Рационал тоог зэрэгт/язгуур'],
    ['zereg-yazguur-ilerhiilel-20.html','Квадрат зэрэг ба язгууртай'],
    ['niilber-kvadrat-20.html','Нийлбэрийн квадрат'],
    ['yalgavar-kvadrat-20.html','Ялгаврын квадрат'],
    ['kvadratuud-ylgavar-20.html','Квадратуудын ялгавар'],
    ['alg-7-tomyo-9.html','7 томьёо — олон үйлдэлт илэрхийлэл (бодолттой)'],
    ['algebr-butarhai-7tomyo-9.html','7 томьёотой алгебрын бутархай 3–4 үйлдэл (хүнд, бодолттой)'],
    ['algebr-butarhai-abc-9.html','7 томьёо + ax²+bx+c задлал (бүүр хүнд, бодолттой)'],
    ['algebr-butarhai-2hyz-9.html','2 хувьсагчтай 4–5 үйлдэл (олимпиадын хүнд, бодолттой)'],
    ['niitleg-2-16.html','Ерөнхий үржигдэхүүн (хүндрүүлсэн)'],
    ['algebr-butarhai-16.html','Алгебрын бутархай хураах'],
    ['algebr-butarhai-2-16.html','Алгебрын бутархай хураах (хүндрүүлсэн)'],
    ['algebr-butarhai-nh-16.html','Алгебрын бутархай нэмэх/хасах'],
    ['algebr-butarhai-uh-16.html','Алгебрын бутархай үржих/хуваах'],
    ['algebr-kvadrat-butarhai-16.html','Квадрат/квадрат бутархай хураах'],
    ['algebr-kvadrat-uh-16.html','Квадрат бутархай үржих/хуваах'],
    ['shts-2-16.html','Хоёр хувьсагчтай ШТС'],
    ['shugaman-tents-bish-16.html','Шугаман тэнцэтгэл биш'],
    ['shuluun-grafik-8.html','Шулууны график'],
    ['shuluun-nalalt-8.html','Шулууны налалт ба график'],
    ['shugaman-urvuu-12.html','Шугаман функцийн урвуу функц'],
  ]],
  ['9-р анги',[
    ['troichlen-zadlal-12.html','Квадрат гурван гишүүнт задлах (алхамжилсан)'],
    ['buleglekh-zadlal-14.html','Бүлэглэх аргаар үржигдэхүүнд задлах'],
    ['irratsional-ilerhiilel-20.html','Иррационал илэрхийлэл'],
    ['algebr-butarhai-buh-16.html','Алгебрын бутархайн бүх үйлдэл'],
    ['algebr-butarhai-buh-2-16.html','Бүх үйлдэл (хүндрүүлсэн)'],
    ['algebr-butarhai-buh-3-16.html','Бүх үйлдэл (илүү хүнд)'],
    ['algebr-buh-4-16.html','Бүх үйлдэл 3–4 үйлдэлтэй (хүнд)'],
    ['alg-7-tomyo-9.html','7 томьёо — олон үйлдэлт илэрхийлэл (бодолттой)'],
    ['algebr-butarhai-7tomyo-9.html','7 томьёотой бутархай 3–4 үйлдэл (хүнд, бодолттой)'],
    ['algebr-butarhai-abc-9.html','7 томьёо + ax²+bx+c задлал (бүүр хүнд, бодолттой)'],
    ['algebr-butarhai-2hyz-9.html','2 хувьсагчтай 4–5 үйлдэл (олимпиадын хүнд, бодолттой)'],
    ['kvadrat-tegshitgel-20.html','Квадрат тэгшитгэл'],
    ['kvadrat-tegshitgel-2-16.html','Квадрат тэгшитгэл (хүндэрсэн)'],
    ['ratsional-tegshitgel-16.html','Рационал тэгшитгэл'],
    ['shts-3-12.html','Гурван хувьсагчтай ШТС'],
    ['songon-9-hard.html','9-р анги сонгон — хүнд бодлого'],
    ['songon-9-4torol.html','9-р анги сонгон — 4 төрлийн бодлого'],
    ['songon-yazguur-4torol.html','Сонгон — язгуурын хүнд бодлого (бодолттой)'],
    ['bisektris-chanar.html','Гурвалжны биссектрисийн чанар (зурагтай)'],
    ['median-chanar.html','Гурвалжны медианы чанар (зурагтай)'],
    ['trig-gar-arga.html','Тригонометр: гарын хурууны арга (0·30·45·60·90 цээжлэх)'],
    ['trig-sin.html','Тригонометр: өнцгийн синус олох'],
    ['trig-cos.html','Тригонометр: өнцгийн косинус олох'],
    ['trig-tan.html','Тригонометр: өнцгийн тангенс олох'],
    ['trig-tal-urt.html','Тригонометр: талын урт олох (30·45·60)'],
    ['trig-ongo-oloh.html','Тригонометр: өнцөг олох (30·45·60)'],
    ['shugaman-urvuu-12.html','Шугаман функцийн урвуу функц'],
    ['koordinat-arga.html','Координатын арга 1 (дундаж цэг ба хоёр цэгийн зай)'],
    ['koordinat-arga-2.html','Координатын арга 2 (параллелограммын дутуу орой)'],
    ['vektor-koordinat.html','Векторын координат 1 (зургаас бич · вектор байгуул)'],
    ['vektor-koordinat-2.html','Векторын координат 2 (цэгээр вектор · урт)'],
    ['vektor-uildel.html','Векторын үйлдэл (зурж нэмэх · координатаар эмхэтгэх)'],
    ['rational-too-9-1.html','1.1 Рационал ба иррационал тоо (9-р анги)'],
    ['kvadrat-yazguur-utga-9-2.html','1.2 Квадрат язгуурын утга ол (9-р анги)'],
    ['yazguur-ilerhiilel-9-2.html','1.2 Язгуур агуулсан илэрхийлэл (9-р анги)'],
    ['standart-helber-9-3.html','1.3 Тооны стандарт хэлбэр (9-р анги)'],
    ['standart-uildel-9-3.html','1.3 Стандарт хэлбэр — үйлдэл ба харьцуулалт (9-р анги)'],
    ['toimloh-1-9-4.html','Тоог тоймлох-1'],
    ['toimloh-2-9-4.html','Тоог тоймлох-2'],
    ['jishig-1-9.html','Жишиг-1'],
    ['jishig-2-9.html','Жишиг-2'],
    ['shalgalt-material-1-9.html','Шалгалтын материал'],
    ['protsent-1-9.html','Процент-1'],
    ['protsent-2-9.html','Процент-2'],
    ['protsent-3-9.html','Процент-3'],
    ['protsent-4-9.html','Процент-4'],
    ['haritsaa-1-9.html','Харьцаа-1'],
    ['haritsaa-2-9.html','Харьцаа-2'],
    ['haritsaa-3-9.html','Харьцаа-3'],
    ['jishig-2-1-9.html','Жишиг-1'],
    ['jishig-2-2-9.html','Жишиг-2'],
    ['shalgalt-material-2-9.html','Шалгалтын материал'],
    ['magadlal-1-9.html','Магадлал-1'],
    ['magadlal-2-9.html','Магадлал-2'],
    ['magadlal-3-9.html','Магадлал-3'],
    ['magadlal-4-9.html','Магадлал-4'],
    ['magadlal-5-9.html','Магадлал-5'],
    ['zadlal-1-9.html','Задлал-1'],
    ['niilber-kv-9-4.html','Нийлбэрийн квадрат'],
    ['yalgavar-kv-9-4.html','Ялгаврын квадрат'],
    ['kv-yalgavar-9-4.html','Квадратуудын ялгавар'],
    ['zadlal-2-9.html','Задлал-2'],
    ['zadlal-3-9.html','Задлал-3'],
    ['turshih-arga-9-4.html','Турших арга (тайлбар)'],
    ['turshih-dasgal-9-4.html','Турших арга — дасгал'],
    ['alg-butarhai-1-9.html','Алгебрын бутархай — хураах'],
    ['alg-butarhai-2-9.html','Алгебрын бутархай — үржүүлэх'],
    ['alg-butarhai-3-9.html','Алгебрын бутархай — хуваах'],
    ['alg-butarhai-4-9.html','Алгебрын бутархай — нэмэх, хасах'],
    ['sistem-1-9.html','Систем — орлуулах арга'],
    ['sistem-2-9.html','Систем — нэмэх арга'],
    ['sistem-3-9.html','Систем — алхам алхмаар'],
    ['sistem-4-9.html','Систем — өгүүлбэртэй бодлого'],
    ['tentsetgel-zavsar-9.html','Тэнцэтгэл биш ба тоон завсар'],
    ['tentsetgel-bodoh-9.html','Шугаман тэнцэтгэл биш бодох'],
    ['tentsetgel-sistem-9.html','Тэнцэтгэл бишийн систем'],
    ['khyalbar-kvadrat-9.html','Хялбар квадрат тэгшитгэл'],
    ['buten-kvadrat-yalgah-9.html','Бүтэн квадрат ялгах арга'],
    ['kvadrat-zadlah-9.html','Квадрат тэгшитгэлийг үржигдэхүүн болгон задлах'],
    ['ratsional-bodoh-9.html','Рационал тэгшитгэл бодох'],
    ['ratsional-kvadrat-9.html','Рационал тэгшитгэл — квадрат тэгшитгэлд шилжих'],
    ['iltgegch-bodoh-9.html','Илтгэгч тэгшитгэл бодох'],
    ['iltgegch-niilmel-9.html','Илтгэгч тэгшитгэл — нийлмэл ба өгүүлбэртэй'],
    ['jishig-4-1-9.html','Жишиг даалгавар 1'],
    ['jishig-4-2-9.html','Жишиг даалгавар 2'],
    ['shalgalt-material-4-1-9.html','Шалгалтын материал-1'],
    ['shalgalt-material-4-2-9.html','Шалгалтын материал-2'],
    ['oorogsorih-1-9.html','Өөрийгөө сорих 1'],
    ['oorogsorih-2-9.html','Өөрийгөө сорих 2'],
    ['oorogsorih-3-9.html','Өөрийгөө сорих 3'],
    ['daraalal-guishuud-9.html','Дараалал — гишүүд олох'],
    ['daraalal-erunhii-9.html','Дараалал — ерөнхий гишүүн олох'],
    ['daraalal-rekurrent-9.html','Дараалал — рекуррент томьёо'],
    ['sistem-grafik-9.html','Систем бодох графикийн арга'],
    ['shuluun-nalalt-9.html','Шулууны налалт'],
    ['urvuu-funkts-9.html','Шугаман функцийн урвуу функц'],
    ['kvadrat-grafik-1-9.html','Квадрат функц — утгын хүснэгт ба график'],
    ['kvadrat-grafik-2-9.html','Квадрат функц — орой, тэгш хэм, шийд'],
    ['jishig-5-1-9.html','V бүлэг — Жишиг даалгавар 1'],
    ['jishig-5-2-9.html','V бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-5-1-9.html','V бүлэг — Шалгалтын материал-1'],
    ['shalgalt-material-5-2-9.html','V бүлэг — Шалгалтын материал-2'],
    ['oorogsorih-4-9.html','Өөрийгөө сорих 4'],
    ['toirog-shurgegch-9.html','Тойргийн шүргэгчийн чанар'],
    ['toirog-hovch-9.html','Тойргийн хөвчийн чанар'],
    ['gadna-onts-9.html','Тойргийн гадна оройтой өнцгийн чанар'],
    ['hovch-shurgegch-onts-9.html','Хөвч ба шүргэгчийн хоорондох өнцгийн чанар'],
    ['ogtlolcson-hovch-9.html','Огтлолцсон хөвчүүдийн чанар'],
    ['shurgegch-ogtlogch-9.html','Шүргэгч ба огтлогчийн чанар'],
    ['ogtlogchuud-9.html','Огтлогчуудын чанар'],
    ['fales-teorem-9.html','Фалесын теорем'],
    ['jishig-6-1-9.html','VI бүлэг — Жишиг даалгавар 1'],
    ['jishig-6-2-9.html','VI бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-6-1-9.html','VI бүлэг — Шалгалтын материал-1'],
    ['shalgalt-material-6-2-9.html','VI бүлэг — Шалгалтын материал-2'],
    ['oorogsorih-5-9.html','Өөрийгөө сорих 5'],
  ]],
  ['10-р анги',[
    ['zereg-teg-sorog-10.html','Тэг ба сөрөг илтгэгчтэй зэрэг — үнэлгээ'],
    ['zereg-teg-sorog-hard-10.html','Тэг ба сөрөг илтгэгчтэй зэрэг — хүндэвтэр (нийлмэл)'],
    ['yazguur-n-zereg-10.html','n зэргийн язгуур ба арифметик язгуур'],
    ['yazguur-n-zereg-hard-10.html','n зэргийн язгуур — хүндэвтэр (нийлмэл, муж, |a|)'],
    ['zereg-yazguur-chanar-10.html','n зэргийн язгуурын чанар'],
    ['zereg-yazguur-chanar-hard-10.html','n зэргийн язгуурын чанар-2'],
    ['ratsional-iltgegch-10.html','Рационал тоон илтгэгчтэй зэрэг'],
    ['ratsional-iltgegch-2-10.html','Рационал тоон илтгэгчтэй зэрэг-2'],
    ['standart-helber-uildel-10.html','Стандарт хэлбэрээр бичсэн тооны үйлдэл'],
    ['jishig-daalgavar-zereg-10.html','II бүлэг — Жишиг даалгавар (нэгтгэсэн)'],
    ['jishig-daalgavar-2-zereg-10.html','II бүлэг — Жишиг даалгавар-2 (олон үйлдэлтэй)'],
    ['shalgalt-material-zereg-10.html','II бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['algebr-ratsional-1-10.html','Рационал илтгэгчтэй алгебрын илэрхийлэл — Түвшин 1'],
    ['algebr-ratsional-2-10.html','Рационал илтгэгчтэй алгебрын илэрхийлэл — Түвшин 2'],
    ['urjigdehuun-zadlah-1-10.html','Үржигдэхүүн болгон задлах 1'],
    ['urjigdehuun-zadlah-2-10.html','Үржигдэхүүн болгон задлах 2'],
    ['algebr-butarhai-urjuuleh-1-10.html','Алгебрын бутархайн үржүүлэх, хуваах 1'],
    ['algebr-butarhai-urjuuleh-2-10.html','Алгебрын бутархайн үржүүлэх, хуваах 2'],
    ['butarhai-nemeh-hasah-1-10.html','Алгебрын бутархайн нэмэх, хасах 1'],
    ['butarhai-nemeh-hasah-2-10.html','Алгебрын бутархайн нэмэх, хасах 2'],
    ['jishig-3-1-10.html','III бүлэг — Жишиг даалгавар 1'],
    ['jishig-3-2-10.html','III бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-3-10.html','III бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['koordinat-sistem-1-10.html','Координатын систем, цэгийн координат 1'],
    ['koordinat-sistem-2-10.html','Координатын систем, цэгийн координат 2'],
    ['shuluu-nalalt-1-10.html','Шулууны налалт 1'],
    ['shuluu-nalalt-2-10.html','Шулууны налалт 2'],
    ['shuluu-tegshitgel-1-10.html','Шулууны тэгшитгэл 1'],
    ['shuluu-tegshitgel-2-10.html','Шулууны тэгшитгэл 2 (графикаас унших)'],
    ['toirog-tegshitgel-1-10.html','Тойргийн тэгшитгэл 1'],
    ['toirog-tegshitgel-2-10.html','Тойргийн тэгшитгэл 2 (графикаас унших)'],
    ['jishig-4-1-10.html','IV бүлэг — Жишиг даалгавар 1'],
    ['jishig-4-2-10.html','IV бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-4-10.html','IV бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['funkts-muj-dur-1-10.html','Функц: утга, тодорхойлогдох муж, дүр 1'],
    ['funkts-mon-eseh-2-10.html','Харгалзаа функц мөн эсэх 2'],
    ['funkts-ax-graf-10.html','y = a/x функцийн график (урвуу пропорциональ)'],
    ['funkts-ax-tegsh-10.html','Графикаас y = a/x тэгшитгэл бичих'],
    ['funkts-axn-muj-10.html','y = axⁿ функц: тодорхойлогдох муж ба дүр'],
    ['funkts-ax2inv-graf-10.html','y = a/x² функцийн график'],
    ['funkts-sqrt-cube-graf-10.html','y = a√x ба y = ax³ функцийн график'],
    ['funkts-exp-graf-10.html','y = aˣ илтгэгч функцийн график'],
    ['funkts-exp-tegsh-10.html','Графикаас илтгэгч функцийн тэгшитгэл'],
    ['shurgegch-nalalt-1-10.html','Шүргэгчийн налалт 1 — олон гишүүнт'],
    ['shurgegch-nalalt-2-10.html','Шүргэгчийн налалт 2 — бутархай, язгуурт'],
    ['jishig-5-1-10.html','V бүлэг — Жишиг даалгавар 1'],
    ['jishig-5-2-10.html','V бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-5-10.html','V бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['shugaman-teng-bish-1-10.html','Шугаман тэнцэтгэл биш 1'],
    ['shugaman-teng-bish-2-10.html','Шугаман тэнцэтгэл биш 2 — давхар, систем'],
    ['kvadrat-teng-bodoh-1-10.html','Квадрат тэгшитгэл бодох 1 (гүйцэд биш, задлан, томьёо)'],
    ['kvadrat-teng-bodoh-2-10.html','Квадрат тэгшитгэл 2 — дискриминант ба хэлбэр'],
    ['shiljih-teng-1-10.html','Квадратад шилждэг тэгшитгэл 1 — биквадрат ба бутархай'],
    ['shiljih-teng-2-10.html','Квадратад шилждэг тэгшитгэл 2 — бодлого'],
    ['shugaman-teng-bish-2huv-10.html','Хоёр хувьсагчтай шугаман тэнцэтгэл биш ба систем'],
    ['shugaman-teng-bish-2huv-2-10.html','Хоёр хувьсагчтай тэнцэтгэл бишийн систем — ахисан'],
    ['iltgegch-teng-1-10.html','Илтгэгч тэгшитгэл 1 — ижил суурьт шилжих арга'],
    ['iltgegch-teng-2-10.html','Илтгэгч тэгшитгэл 2 — шинэ хувьсагч оруулах арга'],
    ['iltgegch-teng-3-10.html','Илтгэгч тэгшитгэл 3 — графикийн арга'],
    ['jishig-6-1-10.html','VI бүлэг — Жишиг даалгавар 1'],
    ['jishig-6-2-10.html','VI бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-6-10.html','VI бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['bagtsan-onts-1-10.html','Тойрогт багтсан өнцөг 1 — багтсан ба төв өнцөг'],
    ['bagtsan-onts-2-10.html','Тойрогт багтсан өнцөг 2 — диаметр, дөрвөн өнцөгт, гурвалжин'],
    ['gurv-bagtsan-toirog-10.html','Гурвалжинд багтсан тойрог — радиус ба талбай'],
    ['gurv-bagtaasan-toirog-10.html','Гурвалжныг багтаасан тойрог — гадаад радиус'],
    ['toirogt-bagtsan-olon-10.html','Тойрогт багтсан олон өнцөгт'],
    ['toirog-bagtaasan-olon-10.html','Тойрог багтаасан олон өнцөгт'],
    ['toirog-hovch-10.html','Тойргийн хөвч — перпендикуляр ба хөвчийн урт'],
    ['toirog-shurgegch-10.html','Тойргийн шүргэгч — урт ба өнцөг'],
    ['shurgegch-hovch-onts-10.html','Шүргэгч-хөвчийн өнцөг ба хоёр шүргэгч'],
    ['toirog-ogtlolcson-10.html','Огтлолцсон хөвч, огтлогч, шүргэгчийн чадал'],
    ['hoyor-toirog-bairshil-10.html','Хоёр тойргийн харилцан байршил'],
    ['tsegiin-geometr-bair-10.html','Цэгийн геометр байр'],
    ['jishig-7-1-10.html','VII бүлэг — Жишиг даалгавар 1'],
    ['jishig-7-2-10.html','VII бүлэг — Жишиг даалгавар 2'],
    ['shalgalt-material-7-10.html','VII бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['olonlog-toon-zavsar-10.html','Олонлог ба тоон завсар'],
    ['grafik-kvadrat-tegsh.html','Графикаас квадрат функцийн тэгшитгэл бичих'],
    ['grafik-ax2.html','Квадрат график: y = ax² (орой эх цэгт)'],
    ['grafik-ax2-c.html','Квадрат график: y = ax² + c (босоо зөөлт)'],
    ['grafik-ax-h2.html','Квадрат график: y = a(x−h)² (хэвтээ зөөлт)'],
    ['grafik-oroin-helber.html','Квадрат график: y = a(x−h)² + k (оройн хэлбэр)'],
    ['grafik-erenhii.html','Квадрат график: y = ax² + bx + c (ерөнхий хэлбэр)'],
    ['kvadrat-grafik-zoolt-8.html','Квадрат график — зөөлтийн аргаар байгуулах (бодолттой)'],
    ['olonlog-hard-1-10.html','Олонлог, элементийн тоо — хүнд'],
    ['olonlog-hard-2-10.html','Тоон завсар ба тэнцэтгэл биш — хүнд'],
    ['olonlog-hard-3-10.html','Олонлогийн тоолол ба параметр — хүнд'],
    ['zereg-teg-sorog-hard-1-10.html','Сөрөг илтгэгчтэй зэргийн хялбарчлал — хүнд'],
    ['zereg-teg-sorog-hard-2-10.html','Бутархай суурьтай ба үсэгт зэрэг — хүнд'],
    ['zereg-teg-sorog-hard-3-10.html','Илтгэгч олох ба жиших — хүнд'],
    ['yazguur-chanar-hard-1-10.html','Язгуурын үржвэр, ноогдвор, давхар язгуур — хүнд'],
    ['yazguur-chanar-hard-2-10.html','Язгуур доорх хувиргалт ба тодорхойлогдох муж — хүнд'],
    ['yazguur-chanar-hard-3-10.html','Язгуурын хэрэглээ, нотолгоо, жиших — хүнд'],
    ['ratsional-iltgegch-hard-1-10.html','Рационал илтгэгчийн чанар ба илтгэгч олох — хүнд'],
    ['ratsional-iltgegch-hard-2-10.html','Рационал илтгэгчтэй тоон илэрхийлэл — хүнд'],
    ['ratsional-iltgegch-hard-3-10.html','Давхар язгуур, задаргаа, жиших — хүнд'],
    ['standart-helber-hard-1-10.html','Стандарт хэлбэрийн нэмэх, хасах, үржүүлэх — хүнд'],
    ['standart-helber-hard-2-10.html','Гинжин үйлдэл, урвуу бодлого, эрэмбэлэл — хүнд'],
    ['alg-ratsional-iltgegch-hard-1-10.html','Рационал илтгэгчтэй илэрхийллийг хялбарчлах — хүнд'],
    ['alg-ratsional-iltgegch-hard-2-10.html','Хуваарийг язгуураас чөлөөлөх — хүнд'],
    ['alg-ratsional-iltgegch-hard-3-10.html','Зэргийн шинж чанар, утга бодох — хүнд'],
    ['urjigdehuun-zadlah-hard-1-10.html','Бүлэглэх ба томьёогоор задлах — хүнд'],
    ['urjigdehuun-zadlah-hard-2-10.html','Кубын томьёо, ерөнхий үржигдэхүүн — хүнд'],
    ['butarhai-urjuuleh-hard-1-10.html','Үржүүлэх, хуваах үйлдэл — хүнд'],
    ['butarhai-urjuuleh-hard-2-10.html','Үйлдлийн дараалал ба хэрэглээ — хүнд'],
    ['butarhai-nemeh-hard-1-10.html','Ерөнхий хуваарь олж нэмэх, хасах — хүнд'],
    ['butarhai-nemeh-hard-2-10.html','Хураагдах нийлбэр ба нийлмэл үйлдэл — хүнд'],
    ['koordinat-sistem-hard-1-10.html','Зай, дундаж цэг, тэгш хэм — хүнд'],
    ['koordinat-sistem-hard-2-10.html','Гурвалжин ба дөрвөн өнцөгтийн төрөл — хүнд'],
    ['koordinat-sistem-hard-3-10.html','Урвуу бодлого: орой ба байрлал — хүнд'],
    ['shuluu-nalalt-hard-1-10.html','Налалтаар параметр олох — хүнд'],
    ['shuluu-nalalt-hard-2-10.html','Налалтыг тэгшитгэл ба зургаас олох — хүнд'],
    ['shuluu-nalalt-hard-3-10.html','Налалтын хэрэглээ: параллель ба төрөл — хүнд'],
    ['shuluu-tegshitgel-hard-1-10.html','Тэгшитгэл бичих ба талбай — хүнд'],
    ['shuluu-tegshitgel-hard-2-10.html','Параметр ба огтлолцлын цэг — хүнд'],
    ['shuluu-tegshitgel-hard-3-10.html','Медиан, гурвалжин, парабол — хүнд'],
    ['toirog-tegshitgel-hard-1-10.html','Тойргийн тэгшитгэл ба радиус — хүнд'],
    ['toirog-tegshitgel-hard-2-10.html','Цэгийн байрлал ба багтсан дүрс — хүнд'],
    ['toirog-tegshitgel-hard-3-10.html','Шулуун ба тойрог, хэрчим таслах — хүнд'],
    ['funkts-muj-hard-1-10.html','Тодорхойлогдох муж ба дүр — хүнд'],
    ['funkts-dur-hard-2-10.html','Функцийн дүр ба параметр — хүнд'],
    ['kvadrat-orgil-hard-1-10.html','Оройн хэлбэр ба параболыг сэргээх — хүнд'],
    ['kvadrat-param-hard-2-10.html','Квадрат функц ба параметр — хүнд'],
    ['kvadrat-grafik-hard-3-10.html','Парабол, шулуун ба талбай — хүнд'],
    ['giperbol-hard-1-10.html','Гиперболын муж, дүр ба тэнцэтгэл биш — хүнд'],
    ['giperbol-hard-2-10.html','Гипербол, шулуун ба хөвч — хүнд'],
    ['zeregt-funkts-hard-1-10.html','Зэрэгт функцийн муж, дүр ба огтлолцол — хүнд'],
    ['zeregt-funkts-hard-2-10.html','Зэрэгт функцийн параметрийг сэргээх — хүнд'],
    ['iltgegch-hard-1-10.html','Илтгэгч функцийн параметр ба дүр — хүнд'],
    ['iltgegch-hard-2-10.html','Илтгэгч тэгшитгэл, тэнцэтгэл биш — хүнд'],
    ['shurgegch-hard-1-10.html','Шүргэгчийн налалт, давхар язгуур — хүнд'],
    ['shurgegch-hard-2-10.html','Шүргэгч, талбай ба урвуу бодлого — хүнд'],
    ['shugaman-tb-hard-1-10.html','Шугаман тэнцэтгэл биш бодох — хүнд'],
    ['shugaman-tb-hard-2-10.html','Тэнцэтгэл бишийн систем ба параметр — хүнд'],
    ['kvadrat-teng-hard-1-10.html','Квадрат тэгшитгэл бодох аргууд — хүнд'],
    ['kvadrat-teng-hard-2-10.html','Параметртэй квадрат тэгшитгэл — хүнд'],
    ['shiljih-teng-hard-1-10.html','Биквадрат ба орлуулах арга — хүнд'],
    ['shiljih-teng-hard-2-10.html','Рационал тэгшитгэл ба хэрэглээ — хүнд'],
    ['2huv-tb-hard-1-10.html','Шийдийн муж ба хагас хавтгай — хүнд'],
    ['2huv-tb-hard-2-10.html','Шугаман программчлалын бодлого — хүнд'],
    ['iltgegch-teng-hard-1-10.html','Ижил суурьт шилжүүлэх арга — хүнд'],
    ['iltgegch-teng-hard-2-10.html','Орлуулах арга ба графикийн арга — хүнд'],
    ['bagtsan-onts-hard-1-10.html','Тойрогт багтсан өнцөг — хүнд'],
    ['bagtsan-onts-hard-2-10.html','Багтсан өнцөг ба нумын хамаарал — хүнд'],
    ['bagtsan-onts-hard-3-10.html','Багтсан өнцөг — холимог бататгал'],
    ['olon-ontsogt-hard-1-10.html','Гурвалжинд багтсан ба багтаасан тойрог — хүнд'],
    ['olon-ontsogt-hard-2-10.html','Тойрогт багтсан ба тойрог багтаасан дөрвөн өнцөгт — хүнд'],
    ['olon-ontsogt-hard-3-10.html','Багтсан ба багтаасан олон өнцөгт — холимог бататгал'],
    ['hovch-shurgegch-hard-1-10.html','Шүргэгч ба хөвчийн үүсгэх өнцөг — хүнд'],
    ['hovch-shurgegch-hard-2-10.html','Хөвч, шүргэгч, огтлогчийн чанар — хүнд'],
    ['hovch-shurgegch-hard-3-10.html','Хөвч, шүргэгч, огтлогч — холимог бататгал'],
    ['hoyor-toirog-hard-1-10.html','Хоёр тойргийн харилцан байршил — хүнд'],
    ['hoyor-toirog-hard-2-10.html','Огтлолцсон ба шүргэлцсэн тойргууд — хүнд'],
    ['tseg-geometr-hard-1-10.html','Цэгийн геометр байр — хүнд'],
    ['tseg-geometr-hard-2-10.html','Геометр байрын тэгшитгэл ба гомотети — хүнд'],
  ]],
  ['11-р анги',[
    ['kvadrat-shinjleh-11.html','Квадрат тэгшитгэлийн шийдийг шинжлэх (дискриминант, параметр)'],
    ['kvadrat-bodoh-11.html','Квадрат тэгшитгэл бодох (задлах·бүтэн квадрат·томьёо·орлуулга)'],
    ['kvadrat-grafik-11.html','Квадрат тэгшитгэл — график байгуулах ба графикаар бодох'],
    ['kvadrat-uguulber-11.html','Квадрат тэгшитгэл зохиож бодох (тоон·геометр·физик)'],
    ['tentsbish-sistem-11.html','Квадрат тэнцэтгэл биш — Тодорхойлолт (систем) арга'],
    ['tentsbish-interval-11.html','Квадрат тэнцэтгэл биш — Интервалын арга (2 жишээтэй)'],
    ['tentsbish-holimog-11.html','Тэнцэтгэл биш — холимог (шугаман·бүтэн квадрат·параметр·хэрэглээ)'],
    ['tentsbish-lavlah-11.html','Квадрат тэнцэтгэл бишийн шийд — лавлах хүснэгт (a>0)'],
    ['tentsbish-grafik-unshih-11.html','Тэнцэтгэл биш — графикаас шийд унших'],
    ['tentsbish-grafik-bodoh-11.html','Тэнцэтгэл биш — график байгуулан бодох (D>0·D=0·D<0)'],
    ['tentsbish-grafik-tusgai-11.html','Тэнцэтгэл биш — задалсан ба тусгай хэлбэр график'],
    ['buleg1-jishig-1.html','I бүлэг — Жишиг даалгавар 1 (100 оноо)'],
    ['buleg1-jishig-2.html','I бүлэг — Жишиг даалгавар 2 (100 оноо)'],
    ['buleg1-shalgalt-1.html','I бүлэг — Шалгалтын материал (100 оноо)'],
    ['sistem-parabol-shuluun-11.html','Парабол ба шулууны харилцан байршил (график)'],
    ['sistem-toirog-giperbol-11.html','Тойрог, гипербол ба шулууны харилцан байршил (график)'],
    ['sistem-grafik-arga-11.html','Тэгшитгэлийн системийг графикийн аргаар бод'],
    ['orluulah-sistem-1-11.html','Систем — орлуулах арга 1 (шугаман·квадрат)'],
    ['orluulah-sistem-2-11.html','Систем — орлуулах арга 2 (симметр·xy·Виет)'],
    ['orluulah-sistem-3-11.html','Систем — орлуулах арга 3 (өгүүлбэр бодлого)'],
    ['urvuu-matrits-1-11.html','Шугаман систем — урвуу матриц 1 (2×2 бодох)'],
    ['urvuu-matrits-2-11.html','Шугаман систем — урвуу матриц 2 (тодорхойлогч, |A|=0)'],
    ['urvuu-matrits-3-11.html','Урвуу матриц 3 (матриц тэгшитгэл, параметр)'],
    ['gauss-jishig-11.html','Гурван хувьсагчтай ШТС — Гауссын арга (жишээ)'],
    ['gauss-sistem-1-11.html','Гурван хувьсагчтай систем — Гаусс 1 (3×3 бодох)'],
    ['gauss-sistem-2-11.html','Гурван хувьсагчтай систем — Гаусс 2 (гүйцээх, хэрэглээ)'],
    ['kramer-2x2-11.html','Крамерын дүрэм — 2×2 систем (тайлбартай)'],
    ['kramer-3x3-11.html','Крамерын дүрэм — 3×3 систем (тайлбартай)'],
    ['buleg2-jishig-1.html','II бүлэг — Жишиг даалгавар 1'],
    ['buleg2-jishig-2.html','II бүлэг — Жишиг даалгавар 2'],
    ['buleg2-shalgalt-1.html','II бүлэг — Шалгалтын материал (тест + задгай)'],
    ['buleg3-jishig-1.html','III бүлэг — Жишиг даалгавар 1'],
    ['buleg3-jishig-2.html','III бүлэг — Жишиг даалгавар 2'],
    ['buleg3-jishig-3.html','III бүлэг — Жишиг даалгавар 3'],
    ['buleg3-shalgalt-1.html','III бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['toon-daraalal-1-11.html','Тоон дараалал — ерөнхий гишүүн, өсөх/буурах'],
    ['toon-daraalal-2-11.html','Тоон дараалал — рекуррент ба нийлбэр'],
    ['arifmetik-progress-1-11.html','Арифметик прогресс — мөн эсэх, ерөнхий гишүүн'],
    ['arifmetik-progress-2-11.html','Арифметик прогресс — гишүүн, дундаж, параметр'],
    ['arifmetik-progress-3-11.html','Арифметик прогрессийн нийлбэр Sₙ'],
    ['arifmetik-progress-4-11.html','Арифметик прогресс — систем ба хэрэглээ'],
    ['geometr-progress-1-11.html','Геометр прогресс — мөн эсэх, ерөнхий гишүүн'],
    ['geometr-progress-2-11.html','Геометр прогресс — гишүүн, дундаж, систем'],
    ['geometr-progress-3-11.html','Геометр прогрессийн нийлбэр Sₙ'],
    ['buleg4-jishig-1.html','IV бүлэг — Жишиг даалгавар 1'],
    ['buleg4-jishig-2.html','IV бүлэг — Жишиг даалгавар 2'],
    ['buleg4-shalgalt-1.html','IV бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['koord-nalalt-1-11.html','Налалт ба нэг шулуун дээрх цэг'],
    ['koord-parallel-2-11.html','Параллель шулуун'],
    ['koord-perp-3-11.html','Перпендикуляр шулуун'],
    ['koord-shuluun-tegsh-4-11.html','Шулууны тэгшитгэл (2 цэг, налалт)'],
    ['koord-par-perp-tegsh-5-11.html','Параллель ба перпендикуляр шулууны тэгшитгэл'],
    ['koord-dundaj-zai-6-11.html','Дундаж цэг ба хэрчмийн урт'],
    ['koord-geometr-7-11.html','Координатын арга — геометр хэрэглээ (параллелограмм, ромб)'],
    ['koord-holimog-8-11.html','Координатын арга — холимог бодлого'],
    ['koord-ogtorgui-1-11.html','Огторгуйн координатын систем, цэгийн байрлал'],
    ['koord-baiguul-2-11.html','Цэг байгуулах ба проекц'],
    ['koord-moch-3-11.html','Мөч (октант) ба координатын тэмдэг'],
    ['koord-hawtgai-zai-4-11.html','Координатын хавтгайтай параллель хавтгай ба зай'],
    ['koord-tegsh-hemt-5-11.html','Огторгуйд тэгш хэмтэй цэг'],
    ['koord-bie-6-11.html','Параллелепипед ба кубын оройн координат'],
    ['koord-zai-1-11.html','Огторгуйд хоёр цэгийн хоорондох зай'],
    ['koord-dundaj-2-11.html','Огторгуйд хэрчмийн дундаж цэг'],
    ['koord-holimog-3-11.html','Зай ба дундаж цэг — хосолсон бодлого'],
    ['buleg5-jishig-1.html','V бүлэг — Жишиг даалгавар 1'],
    ['buleg5-jishig-2.html','V бүлэг — Жишиг даалгавар 2'],
    ['buleg5-shalgalt-1.html','V бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['trig-ergelt-1-11.html','Эргэлтийн өнцөг ба давхацсан өнцөг'],
    ['trig-moch-2-11.html','Өнцгийн мөч'],
    ['trig-temdeg-3-11.html','Тригонометр функцийн тэмдэг'],
    ['trig-toirog-4-11.html','Нэгж тойрог: координат, нум ба сектор'],
    ['trig-utga-1-11.html','Тусгай ба том өнцгийн утга'],
    ['trig-ilerhiill-2-11.html','Тригонометр илэрхийллийн утга бодох'],
    ['trig-zavsar-3-11.html','Утгын завсар, оршин байх ба их/бага'],
    ['trig-adiltgal-1-11.html','Тригонометр илэрхийлэл хялбарчлах'],
    ['trig-adiltgal-2-11.html','Тригонометр адилтгал — утга олох ба батлах'],
    ['buleg6-jishig-1.html','VI бүлэг — Жишиг даалгавар 1'],
    ['buleg6-jishig-2.html','VI бүлэг — Жишиг даалгавар 2'],
    ['buleg6-shalgalt-1.html','VI бүлэг — Шалгалтын материал (тест + задгай, олон хувилбар)'],
    ['funkts-muj-11.html','Функц · тодорхойлогдох муж · адилтгал тэнцүү функц'],
    ['funkts-illerhiile-11.html','Хэмжигдэхүүнийг функцээр илэрхийлэх (геометр, хэрэглээ)'],
    ['graf-funkts-eseh-11.html','Муруй функцийн график мөн эсэх (босоо шулуун)'],
    ['zeregt-muj-11.html','Зэрэгт функц — тодорхойлогдох ба утгын муж'],
    ['zeregt-shinj-11.html','Зэрэгт функц — график ба өсөх/буурах'],
    ['harilcan-neg-1-11.html','Харилцан нэг утгатай функцийг тодорхойлох (томьёо, график)'],
    ['harilcan-neg-2-11.html','Харилцан нэг утгатай функц — диаграм ба тоолол'],
    ['davhar-bodoh-1-11.html','Давхар функц бодох — g(f(x)), f(g(x))'],
    ['davhar-utga-2-11.html','Давхар функцийн утга — хүснэгт, тэгшитгэл'],
    ['davhar-muj-3-11.html','Давхар функц — тодорхойлогдох муж, функциональ тэгшитгэл, параметр'],
    ['urvuu-baih-1-11.html','Урвуутай эсэх — томьёо ба хэвтээ шулуун'],
    ['urvuu-oloh-2-11.html','Урвуу функцийг олох (x,y солих арга)'],
    ['urvuu-chanar-3-11.html','Урвуу функцийн шинж — шалгах, утга, параметр'],
    ['osokh-buurakh-muj-1-11.html','Өсөх/буурах завсар — томьёогоор'],
    ['osokh-buurakh-graf-2-11.html','Графикаас өсөх/буурах ба монотон завсрын утгын муж'],
    ['osokh-buurakh-param-3-11.html','Өсөх/буурах — утгын муж ба цэгээс параметр ол'],
    ['tegsh-sondgoi-1-11.html','Тэгш/сондгой функц — шалгах (томьёо, график)'],
    ['tegsh-sondgoi-param-2-11.html','Тэгш/сондгой функц — параметр ол'],
    ['kvadrat-tentsbish-grafik.html','Квадрат тэнцэтгэл биш — графикийн арга'],
    ['tegshitgel-sistem-4torol.html','Шугаман бус тэгшитгэлийн систем (орлуулах·график, бодолттой)'],
    ['matrits-urvuu-sistem-12.html','Систем — урвуу матрицын арга (бодолттой)'],
    ['iltgegch-tegshitgel-16.html','Илтгэгч тэгшитгэл'],
    ['matrits-2x2-20.html','2×2 матриц (тодорхойлогч/урвуу)'],
    ['matrits-3x3-det-12.html','3×3 матрицын тодорхойлогч'],
    ['kramer-3-6.html','Крамерын дүрэм (3 хувьсагч)'],
  ]],
  ['12-р анги',[
    ['modul-12.html','Тооны модул (радикал·лог·тригонометр)'],
    ['modul-tegshitgel-12.html','Модултай тэгшитгэл |ax+b|=c'],['modul-tegshitgel-2-12.html','Модултай тэгшитгэл — нийлмэл (|ax+b|=cx+d, давхар, |x²−m|=n)'],['modul-tegshitgel-3-12.html','Модултай тэгшитгэл |f(x)|=|g(x)| (хоёр тал модультай)'],
    ['modul-tentsetgel-bish-12.html','Модул агуулсан тэнцэтгэл биш (шийд — тоон завсар)'],
    ['modul-tentsetgel-bish-2-12.html','Модул агуулсан тэнцэтгэл биш — системээр |ax+b|>cx+d'],
    ['modul-tentsetgel-bish-3-12.html','Модул тэнцэтгэл биш |ax+b|>|cx+d| (хоёр тал модультай, f²>g²)'],
    ['modul-ab-kvadrat-12.html','|a|=|b|⇒a²=b² — тэгшитгэл ба тэнцэтгэл биш холимог (коэффициенттэй)'],
    ['modul-orluulga-kvadrat-12.html','|x|²=x² орлуулга — квадрат тэгшитгэл ба тэнцэтгэл биш (y=|x|)'],
    ['modul-radikal-12.html','|x|=√(x²) — √(бүтэн квадрат)=|шугаман| тэгшитгэл ба тэнцэтгэл биш'],
    ['modul-shalgalt-12.html','Модуль — Шалгалтын жишиг даалгавар (бүх төрөл холимог)'],
    ['modul-shalgalt-material-12.html','Модуль — Шалгалтын материал (10 тест + 4 задгай, хариутай)'],
  ]],
];
window.WS_CAMB=[
  ['Бүлэг 4 · Бутархай, аравт, хувь',[
    ['camb-4a-factors.html','4A · Хуваагч ба үржвэр'],
    ['camb-4b-hcf-lcm.html','4B · ХИЕХ ба ХБЕХ'],
    ['camb-4d-equiv-fraction.html','4D · Эквивалент/энгийн бутархай'],
    ['camb-4e-mixed-improper.html','4E · Холимог ↔ энгийн бус бутархай'],
    ['camb-4f-compare-fraction.html','4F · Бутархай харьцуулах·эрэмбэлэх'],
    ['camb-4g-decimal-order.html','4G · Аравтын бутархай харьцуулах'],
    ['camb-4h-round-decimal.html','4H · Аравтын бутархай тойролт'],
    ['camb-4i-dec-frac.html','4I · Аравт ↔ бутархай хөрвүүлэх'],
    ['camb-4j-perc-frac-dec.html','4J · Хувь ↔ бутархай ↔ аравт'],
    ['camb-4k-dec-perc.html','4K · Аравт ↔ хувь хөрвүүлэх'],
    ['camb-4l-frac-perc.html','4L · Бутархай ↔ хувь хөрвүүлэх'],
    ['camb-4m-perc-quantity.html','4M · Тооны хувь олох'],
    ['camb-4n-compare.html','4N · Харьцаа: хэдэн % / ямар бутархай'],
  ]],
];
