// Дасгалын төвийн каталог — worksheets.html ба plan.html хуваалцана
window.WS_LIST=[
  ['3-р анги',[
    ['urjver-hurd.html','Үржвэрийн хүрд (цээжлэх хүснэгт)'],
    ['urjver-3x2-20.html','3 × 2 оронтой үржвэр'],
    ['huvaalt-3x2-12.html','3 ÷ 2 оронтой (баганан хуваалт)'],
    ['huvaalt-mongol-12.html','Баганан хуваалт — Монгол хэлбэр'],
    ['tegshitgel-3.html','Тэгшитгэл (нэмэх·хасах)'],
  ]],
  ['4-р анги',[
    ['urjver-4x3-12.html','4 × 3 оронтой үржвэр'],
    ['huvaalt-4x2-12.html','4 ÷ 2 оронтой (Монгол хэлбэр)'],
    ['huvaalt-4x3-12.html','4 ÷ 3 оронтой (Монгол хэлбэр)'],
    ['huvaalt-tom-12.html','5–6 ÷ 2–3 оронтой хуваалт'],
    ['uguulber-4-hard.html','Өгүүлбэртэй бодлого — хүндэвтэр (бодолттой)'],
    ['butarhai-urjih-18.html','Бутархай үржих'],
    ['butarhai-nemeh-18.html','Бутархай нэмэх'],
    ['butarhai-hasah-18.html','Бутархай хасах'],
    ['butarhai-huvaah-16.html','Бутархай хуваах — эргүүлж үржүүлэх'],
    ['butarhai-jish-4.html','Бутархай жиших (<, >, =)'],
    ['arav-toymloh-4.html','Аравтын бутархайг тоймлох (бүхэл·аравт)'],
    ['tegshitgel-4.html','Тэгшитгэл (+ − × ÷ нэг алхам)'],
  ]],
  ['5-р анги',[
    ['huvaalt-5x2-12.html','5 ÷ 2 оронтой (Монгол хэлбэр)'],
    ['huvaalt-5x3-12.html','5 ÷ 3 оронтой (Монгол хэлбэр)'],
    ['huvaalt-6x3-12.html','6 ÷ 3 оронтой (Монгол хэлбэр)'],
    ['herchim-arga-12.html','Хэрчмийн арга (нийлбэр-зөрүү)'],
    ['uguulber-4angi-12.html','4-р анги — өгүүлбэртэй бодлого (хүндэвтэр)'],
    ['hurd-bodlogo-12.html','Хурдны бодлого'],
    ['zoruu-bodlogo-12.html','Зөрүү ба харьцуулах'],
    ['butarhai-uildluud-10.html','Энгийн бутархайн үйлдлүүд (+ − × ÷)'],
    ['butarhai-urjih-18.html','Бутархай үржих'],
    ['butarhai-nemeh-18.html','Бутархай нэмэх'],
    ['butarhai-hasah-18.html','Бутархай хасах'],
    ['butarhai-huvaah-16.html','Бутархай хуваах — эргүүлж үржүүлэх'],
    ['butarhai-hura-18.html','Бутархай хураах (засагдах)'],
    ['butarhai-holimog-16.html','Холимог ↔ энгийн бус бутархай'],
    ['butarhai-ekvivalent-24.html','Эквивалент бутархай (дутуу тоо)'],
    ['butarhai-jish-5.html','Бутархай жиших (холбоотой хуваарь)'],
    ['arav-butarhai-nemeh-18.html','Аравтын бутархай нэмэх'],
    ['arav-butarhai-hasah-18.html','Аравтын бутархай хасах'],
    ['arav-butarhai-urjih-18.html','Аравтын бутархай үржих'],
    ['arav-butarhai-huvaah-18.html','Аравтын бутархай хуваах'],
    ['arav-butarhai-ilerhiilel-12.html','Аравтын бутархай — илэрхийлэл (үйлдлийн дараалал)'],
    ['arav-engiin-holimog-12.html','Аравт ба энгийн бутархай — холимог илэрхийлэл'],
    ['arav-toymloh-5.html','Аравтын бутархайг тоймлох (аравт·зуут)'],
    ['tegshitgel-5.html','Тэгшитгэл (хоёр алхам ax+b=c)'],
  ]],
  ['6-р анги',[
    ['arav-toymloh-6.html','Аравтын бутархайг тоймлох (аравт·зуут·мянгат)'],
    ['arav6-nemeh.html','Аравтын бутархай нэмэх (гурван гишүүнт · хүнд)'],
    ['arav6-hasah.html','Аравтын бутархай хасах (дараалсан · хүнд)'],
    ['arav6-urjih.html','Аравтын бутархай үржих (2 орон × аравт/бүхэл)'],
    ['arav6-huvaah.html','Аравтын бутархай хуваах (аравт хуваагчаар)'],
    ['arav6-ilerhiilel.html','Аравтын бутархай илэрхийлэл (хаалт·олон үйлдэл)'],
    ['arav6-holimog.html','Аравт ба энгийн бутархай холимог (хүнд)'],
    ['numshul-nemeh-hasah-12.html','Тоон шулуун дээрх нэмэх/хасах'],
    ['negativ-too-100.html','Сөрөг тоо нэмэх/хасах (100)'],
    ['temdegt-nemeh-hasah-60.html','Бүхэл тоо нэмэх/хасах (бүх хэлбэр)'],
    ['temdegt-urjhuv-20.html','Эерэг сөрөг үржих/хуваах'],
    ['temdegt-ilerhiilel-20.html','Эерэг сөрөг илэрхийлэл'],
    ['anhny-too-100.html','Анхны тоонууд (1–100)'],
    ['anhny-zadlal-16.html','Анхны үржигдэхүүнд задлах'],
    ['hieh-hbeh-16.html','ХИЕХ ба ХБЕХ (баганан)'],
    ['izil-huvaari-16.html','Ижил хуваарьтай болгох'],
    ['huvari-arav-protsent-16.html','Бутархай·аравт·хувь шилжүүлэх'],
    ['butarhai-uildluud-10.html','Энгийн бутархайн үйлдлүүд (+ − × ÷)'],
    ['butarhai-huvaah-16.html','Бутархай хуваах — эргүүлж үржүүлэх'],
    ['algebr-gishuun-negtgeh-16.html','Ижил гишүүд нэгтгэх'],
    ['algebr-haalt-zadlah-16.html','Хаалт задлах (нэг хаалт)'],
    ['algebr-hyalbarchlah-14.html','Алгебр илэрхийлэл хялбарчлах (хаалт задлах)'],
    ['butarhai-hura-18.html','Бутархай хураах (засагдах)'],
    ['butarhai-holimog-16.html','Холимог ↔ энгийн бус бутархай'],
    ['butarhai-ekvivalent-24.html','Эквивалент бутархай (дутуу тоо)'],
    ['butarhai-jish-6.html','Бутархай жиших (хөндлөн·энгийн бус·холимог)'],
    ['tegshitgel-6.html','Тэгшитгэл (сөрөгтэй хоёр алхам)'],
    ['hamar-ongo.html','Хамар өнцөг 1'],
    ['hamar-ongo-2.html','Хамар өнцөг 2 (илэрхийлэлтэй)'],
    ['bosoo-ongo.html','Босоо өнцөг 1'],
    ['bosoo-ongo-2.html','Босоо өнцөг 2 (илэрхийлэлтэй)'],
    ['gurvaljin-ongo.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 1'],
    ['gurvaljin-ongo-2.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['olon-ongogt-ongo.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 1 (4·5·6)'],
    ['olon-ongogt-ongo-2.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
  ]],
  ['7-р анги',[
    ['daraalal-zui-togtol-12.html','Дарааллын зүй тогтлыг олох'],
    ['arifmetik-progress-12.html','Арифметик прогресс — n дүгээр гишүүн'],
    ['algebr-gishuun-negtgeh-16.html','Ижил гишүүд нэгтгэх'],
    ['tegshitgel-7.html','Тэгшитгэл (хоёр талд хувьсагч·хаалт)'],
    ['algebr-haalt-zadlah-16.html','Хаалт задлах (нэг хаалт)'],
    ['algebr-hyalbarchlah-14.html','Алгебр илэрхийлэл хялбарчлах (хаалт задлах)'],
    ['aravt-zereg-16.html','10-ын бүхэл илтгэгчтэй зэрэг'],
    ['kvadrat-zereg-20.html','Квадрат зэрэг'],
    ['zereg-chanar-30.html','Зэргийн чанарууд (30)'],
    ['ratsional-nemeh-hasah-20.html','Рационал нэмэх/хасах'],
    ['ratsional-urjih-huvaah-20.html','Рационал үржих/хуваах'],
    ['ratsional-toon-ilerhiilel-16.html','Рационал тоон илэрхийлэл'],
    ['neg-olon-gishuunt-20.html','Нэг × олон гишүүнт'],
    ['olon-olon-gishuunt-16.html','Олон × олон гишүүнт'],
    ['olon-gishuunt-emhetgel-20.html','Олон гишүүнт хялбаржуулах'],
    ['standart-emhetgel-16.html','Стандарт хэлбэрт эмхэтгэх'],
    ['niitleg-uurjigdehuun-20.html','Ерөнхий үржигдэхүүн хаалтнаас'],
    ['niitleg-monom-16.html','Ерөнхий үржигдэхүүн (нэг гишүүнт x,y)'],
    ['gishuunchlen-urjih-16.html','Гишүүнчлэн үржүүлж хялбарчлах'],
    ['shugaman-tegshitgel-16.html','Шугаман тэгшитгэл'],
    ['hamar-ongo.html','Хамар өнцөг 1'],
    ['hamar-ongo-2.html','Хамар өнцөг 2 (илэрхийлэлтэй)'],
    ['bosoo-ongo.html','Босоо өнцөг 1'],
    ['bosoo-ongo-2.html','Босоо өнцөг 2 (илэрхийлэлтэй)'],
    ['gurvaljin-ongo.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 1'],
    ['gurvaljin-ongo-2.html','Гурвалжны дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['olon-ongogt-ongo.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 1 (4·5·6)'],
    ['olon-ongogt-ongo-2.html','Олон өнцөгтийн дотоод өнцгүүдийн нийлбэр 2 (илэрхийлэлтэй)'],
    ['solbison-ongo.html','Солбисон өнцөг (зэрэгцээ шулуун ба огтлогч)'],
    ['gadaad-ongo.html','Гурвалжны гадаад өнцөг'],
  ]],
  ['8-р анги',[
    ['zereg-uildel-12.html','Зэрэгтэй илэрхийлэл — үйлдэл гүйцэтгэх'],
    ['zereg-chanar-hard-10.html','Зэргийн чанар — хүндэрсэн (тооцоол)'],
    ['yazguur-hyalbarchlah-20.html','Язгуур хялбарчлах (үржигдэхүүн гаргах)'],
    ['rats-zereg-yazguur-ilerhiilel-16.html','Зэрэг ба язгууртай илэрхийлэл (хосолсон)'],
    ['rats-zeregt-18.html','Рационал тоог зэрэгт дэвшүүлэх'],
    ['rats-yazguur-gargah-18.html','Рационал тооноос язгуур гаргах'],
    ['kvadrat-yazguur-20.html','Квадрат язгуур'],
    ['kvadrat-yazguur-buhel-20.html','Квадрат язгуур (бүхэл хариутай)'],
    ['kub-zereg-yazguur-16.html','Куб зэрэг ба куб язгуур'],
    ['ratsional-yazguur-20.html','Рационал тооны язгуур'],
    ['rats-zereg-yazguur-16.html','Рационал тоог зэрэгт/язгуур'],
    ['zereg-yazguur-ilerhiilel-20.html','Квадрат зэрэг ба язгууртай'],
    ['niilber-kvadrat-20.html','Нийлбэрийн квадрат'],
    ['yalgavar-kvadrat-20.html','Ялгаврын квадрат'],
    ['kvadratuud-ylgavar-20.html','Квадратуудын ялгавар'],
    ['alg-7-tomyo-9.html','7 томьёо — олон үйлдэлт илэрхийлэл (бодолттой)'],
    ['algebr-butarhai-7tomyo-9.html','7 томьёотой алгебрын бутархай 3–4 үйлдэл (хүнд, бодолттой)'],
    ['algebr-butarhai-abc-9.html','7 томьёо + ax²+bx+c задлал (бүүр хүнд, бодолттой)'],
    ['algebr-butarhai-2hyz-9.html','2 хувьсагчтай 4–5 үйлдэл (олимпиадын хүнд, бодолттой)'],
    ['niitleg-2-16.html','Ерөнхий үржигдэхүүн (хүндрүүлсэн)'],
    ['algebr-butarhai-16.html','Алгебрын бутархай хураах'],
    ['algebr-butarhai-2-16.html','Алгебрын бутархай хураах (хүндрүүлсэн)'],
    ['algebr-butarhai-nh-16.html','Алгебрын бутархай нэмэх/хасах'],
    ['algebr-butarhai-uh-16.html','Алгебрын бутархай үржих/хуваах'],
    ['algebr-kvadrat-butarhai-16.html','Квадрат/квадрат бутархай хураах'],
    ['algebr-kvadrat-uh-16.html','Квадрат бутархай үржих/хуваах'],
    ['shts-2-16.html','Хоёр хувьсагчтай ШТС'],
    ['shugaman-tents-bish-16.html','Шугаман тэнцэтгэл биш'],
    ['shuluun-grafik-8.html','Шулууны график'],
    ['shuluun-nalalt-8.html','Шулууны налалт ба график'],
    ['shts-grafik-8.html','ШТС графикийн аргаар'],
    ['shugaman-urvuu-12.html','Шугаман функцийн урвуу функц'],
  ]],
  ['9-р анги',[
    ['troichlen-zadlal-12.html','Квадрат гурван гишүүнт задлах (алхамжилсан)'],
    ['buleglekh-zadlal-14.html','Бүлэглэх аргаар үржигдэхүүнд задлах'],
    ['irratsional-ilerhiilel-20.html','Иррационал илэрхийлэл'],
    ['algebr-butarhai-buh-16.html','Алгебрын бутархайн бүх үйлдэл'],
    ['algebr-butarhai-buh-2-16.html','Бүх үйлдэл (хүндрүүлсэн)'],
    ['algebr-butarhai-buh-3-16.html','Бүх үйлдэл (илүү хүнд)'],
    ['algebr-buh-4-16.html','Бүх үйлдэл 3–4 үйлдэлтэй (хүнд)'],
    ['alg-7-tomyo-9.html','7 томьёо — олон үйлдэлт илэрхийлэл (бодолттой)'],
    ['algebr-butarhai-7tomyo-9.html','7 томьёотой бутархай 3–4 үйлдэл (хүнд, бодолттой)'],
    ['algebr-butarhai-abc-9.html','7 томьёо + ax²+bx+c задлал (бүүр хүнд, бодолттой)'],
    ['algebr-butarhai-2hyz-9.html','2 хувьсагчтай 4–5 үйлдэл (олимпиадын хүнд, бодолттой)'],
    ['kvadrat-tegshitgel-20.html','Квадрат тэгшитгэл'],
    ['kvadrat-tegshitgel-2-16.html','Квадрат тэгшитгэл (хүндэрсэн)'],
    ['ratsional-tegshitgel-16.html','Рационал тэгшитгэл'],
    ['shts-3-12.html','Гурван хувьсагчтай ШТС'],
    ['songon-9-hard.html','9-р анги сонгон — хүнд бодлого'],
    ['songon-9-4torol.html','9-р анги сонгон — 4 төрлийн бодлого'],
    ['songon-yazguur-4torol.html','Сонгон — язгуурын хүнд бодлого (бодолттой)'],
    ['bisektris-chanar.html','Гурвалжны биссектрисийн чанар (зурагтай)'],
    ['median-chanar.html','Гурвалжны медианы чанар (зурагтай)'],
    ['trig-gar-arga.html','Тригонометр: гарын хурууны арга (0·30·45·60·90 цээжлэх)'],
    ['trig-sin.html','Тригонометр: өнцгийн синус олох'],
    ['trig-cos.html','Тригонометр: өнцгийн косинус олох'],
    ['trig-tan.html','Тригонометр: өнцгийн тангенс олох'],
    ['trig-tal-urt.html','Тригонометр: талын урт олох (30·45·60)'],
    ['trig-ongo-oloh.html','Тригонометр: өнцөг олох (30·45·60)'],
    ['shugaman-urvuu-12.html','Шугаман функцийн урвуу функц'],
    ['koordinat-arga.html','Координатын арга 1 (дундаж цэг ба хоёр цэгийн зай)'],
    ['koordinat-arga-2.html','Координатын арга 2 (параллелограммын дутуу орой)'],
    ['vektor-koordinat.html','Векторын координат 1 (зургаас бич · вектор байгуул)'],
    ['vektor-koordinat-2.html','Векторын координат 2 (цэгээр вектор · урт)'],
    ['vektor-uildel.html','Векторын үйлдэл (зурж нэмэх · координатаар эмхэтгэх)'],
  ]],
  ['10-р анги',[
    ['grafik-ax2.html','Квадрат график: y = ax² (орой эх цэгт)'],
    ['grafik-ax2-c.html','Квадрат график: y = ax² + c (босоо зөөлт)'],
    ['grafik-ax-h2.html','Квадрат график: y = a(x−h)² (хэвтээ зөөлт)'],
    ['grafik-oroin-helber.html','Квадрат график: y = a(x−h)² + k (оройн хэлбэр)'],
    ['grafik-erenhii.html','Квадрат график: y = ax² + bx + c (ерөнхий хэлбэр)'],
    ['kvadrat-grafik-zoolt-8.html','Квадрат график — зөөлтийн аргаар байгуулах (бодолттой)'],
  ]],
  ['11-р анги',[
    ['kvadrat-tentsbish-grafik.html','Квадрат тэнцэтгэл биш — графикийн арга'],
    ['tegshitgel-sistem-4torol.html','Шугаман бус тэгшитгэлийн систем (орлуулах·график, бодолттой)'],
    ['matrits-urvuu-sistem-12.html','Систем — урвуу матрицын арга (бодолттой)'],
    ['iltgegch-tegshitgel-16.html','Илтгэгч тэгшитгэл'],
    ['matrits-2x2-20.html','2×2 матриц (тодорхойлогч/урвуу)'],
    ['matrits-3x3-det-12.html','3×3 матрицын тодорхойлогч'],
    ['kramer-3-6.html','Крамерын дүрэм (3 хувьсагч)'],
  ]],
  ['12-р анги',[
    ['modul-12.html','Тооны модул (радикал·лог·тригонометр)'],
    ['modul-tegshitgel-12.html','Модултай тэгшитгэл |ax+b|=c'],['modul-tegshitgel-2-12.html','Модултай тэгшитгэл — нийлмэл (|ax+b|=cx+d, давхар, |x²−m|=n)'],['modul-tegshitgel-3-12.html','Модултай тэгшитгэл |f(x)|=|g(x)| (хоёр тал модультай)'],
  ]],
];
window.WS_CAMB=[
  ['Бүлэг 4 · Бутархай, аравт, хувь',[
    ['camb-4a-factors.html','4A · Хуваагч ба үржвэр'],
    ['camb-4b-hcf-lcm.html','4B · ХИЕХ ба ХБЕХ'],
    ['camb-4d-equiv-fraction.html','4D · Эквивалент/энгийн бутархай'],
    ['camb-4e-mixed-improper.html','4E · Холимог ↔ энгийн бус бутархай'],
    ['camb-4f-compare-fraction.html','4F · Бутархай харьцуулах·эрэмбэлэх'],
    ['camb-4g-decimal-order.html','4G · Аравтын бутархай харьцуулах'],
    ['camb-4h-round-decimal.html','4H · Аравтын бутархай тойролт'],
    ['camb-4i-dec-frac.html','4I · Аравт ↔ бутархай хөрвүүлэх'],
    ['camb-4j-perc-frac-dec.html','4J · Хувь ↔ бутархай ↔ аравт'],
    ['camb-4k-dec-perc.html','4K · Аравт ↔ хувь хөрвүүлэх'],
    ['camb-4l-frac-perc.html','4L · Бутархай ↔ хувь хөрвүүлэх'],
    ['camb-4m-perc-quantity.html','4M · Тооны хувь олох'],
    ['camb-4n-compare.html','4N · Харьцаа: хэдэн % / ямар бутархай'],
  ]],
];
